### ISSUE TITLE
 make is compatible to php8 

### ISSUE THREAD

**Issue by gildastema** [Ang3/php-xmlrpc-client#1]

**Comment by bastien-wink** [comment]
Is someone planning to update this to PHP 8 ?

**Comment by gildastema** [comment]
i think is compatible

**Comment by bastien-wink** [comment]
I tested with phpcompatibility/php-compatibility, no issue found.

**Comment by Ang3** [comment]
See [v1.0.3](https://github.com/Ang3/php-xmlrpc-client/releases/tag/v1.0.3).
